Repository glimmerjs/glimmer-vm, pull requests merged in 2019-02, with the labels that each got.

#912 [HOTFIX] Move opcode metadata to @glimmer/debug package
  build/debug.js
  packages/@glimmer/debug/index.ts
  packages/@glimmer/debug/lib/opcode-metadata.ts
  packages/@glimmer/opcode-compiler/lib/debug.ts
  packages/@glimmer/runtime/lib/opcodes.ts
  packages/@glimmer/vm/index.ts
  testem.js
Labels: internal

#914 Temporarily disable smoke test on Travis
  .travis.yml
Labels: internal

#913 Expose template metadata to AST plugins
  packages/@glimmer/bundle-compiler/lib/bundle-compiler.ts
  packages/@glimmer/compiler/lib/template-compiler.ts
  packages/@glimmer/integration-tests/lib/modes/aot/delegate.ts
  packages/@glimmer/syntax/lib/parser/tokenizer-event-handlers.ts
  packages/@glimmer/syntax/test/plugin-node-test.ts
  test/index.html
Labels: enhancement

#911 Update Guides to include more complete steps
  guides/embedding/02-minimum-environment.md
  guides/embedding/03-adding-state.md
  guides/embedding/04-external-helpers.md
  guides/embedding/05-components.md
Labels: documentation
