Repository glimmerjs/glimmer-vm, pull requests merged in 2020-04, with the labels that each got.

#1071 @glimmer/syntax: Bump minimum handlebars.js version
  package.json
  packages/@glimmer/syntax/package.json
  yarn.lock
Labels: bug

#1073 Ensure errors during component creation do not cause secondary errors during DOM cleanup
  packages/@glimmer/integration-tests/lib/render-test.ts
  packages/@glimmer/integration-tests/lib/suites/components.ts
  packages/@glimmer/interfaces/lib/dom/attributes.d.ts
  packages/@glimmer/runtime/lib/vm/append.ts
  packages/@glimmer/runtime/lib/vm/element-builder.ts
Labels: bug

#1074 Backport: Properly cleanup the element builder in a try/finally
  packages/@glimmer/runtime/lib/vm/append.ts
  packages/@glimmer/runtime/lib/vm/element-builder.ts
  packages/@glimmer/test-helpers/lib/render-test.ts
  packages/@glimmer/test-helpers/lib/suites/components.ts
Labels: bug

#1075 Update main key in package json to reference es2017 bundles
  build/broccoli/write-package-json.js
  ember-cli-build.js
Labels: breaking

#1078 Fix package.json versions.
  package.json
  packages/@glimmer/bundle-compiler/package.json
  packages/@glimmer/compiler/package.json
  packages/@glimmer/debug/package.json
  packages/@glimmer/dom-change-list/package.json
  packages/@glimmer/encoder/package.json
  packages/@glimmer/integration-tests/package.json
  packages/@glimmer/node/package.json
  packages/@glimmer/opcode-compiler/package.json
  packages/@glimmer/program/package.json
  packages/@glimmer/reference/package.json
  packages/@glimmer/runtime/package.json
  packages/@glimmer/syntax/package.json
  packages/@glimmer/util/package.json
  packages/@glimmer/vm/package.json
  packages/@glimmer/wire-format/package.json
  yarn.lock
Labels: internal

#1079 Ensure overriding with an empty Hash does not add extra whitespace.
  packages/@glimmer/syntax/lib/generation/printer.ts
  packages/@glimmer/syntax/test/generation/print-test.ts
Labels: bug

#1056 Reduce template size increase
  packages/@glimmer/compiler/lib/builder-interface.ts
  packages/@glimmer/compiler/lib/builder.ts
  packages/@glimmer/compiler/lib/compiler-ops.ts
  packages/@glimmer/compiler/lib/javascript-compiler.ts
  packages/@glimmer/compiler/lib/template-compiler.ts
  packages/@glimmer/compiler/lib/wire-format-debug.ts
  packages/@glimmer/integration-tests/lib/suites/custom-dom-helper.ts
  packages/@glimmer/integration-tests/test/updating-test.ts
  packages/@glimmer/interfaces/lib/compile/wire-format.d.ts
  packages/@glimmer/opcode-compiler/lib/syntax/expressions.ts
  packages/@glimmer/opcode-compiler/lib/syntax/macros.ts
  packages/@glimmer/opcode-compiler/lib/syntax/statements.ts
  packages/@glimmer/opcode-compiler/lib/utils.ts
Labels: breaking

#1081 Fix key uniqueness implementation
  packages/@glimmer/reference/lib/iterable-impl.ts
  packages/@glimmer/reference/test/iterable-impl-test.ts
Labels: bug

#1080 Ensure destructors run for items added to an `{{#each` after initial render
  packages/@glimmer/integration-tests/test/updating-test.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/lists.ts
  packages/@glimmer/runtime/lib/vm/append.ts
  packages/@glimmer/runtime/lib/vm/update.ts
Labels: bug
