Repository glimmerjs/glimmer-vm, pull requests merged in 2020-02, with the labels that each got.

#1024 syntax/traversal: Add `parents()` generator method to the `Path` class
  packages/@glimmer/syntax/lib/traversal/path.ts
  packages/@glimmer/syntax/test/traversal/visiting-node-test.ts
Labels: enhancement

#1030 Add @glimmer/env to @glimmer/util's package.json.
  packages/@glimmer/util/package.json
Labels: bug

#1031 [BUGFIX] Update HasBlockParams metadata
  build/broccoli/build-packages.js
  build/broccoli/strip-glimmer-utilities.js
  build/broccoli/transpile-to-es5.js
  package.json
  packages/@glimmer/compiler/lib/template-compiler.ts
  packages/@glimmer/debug/lib/opcode-metadata.ts
  packages/@glimmer/local-debug-flags/index.ts
  packages/@glimmer/opcode-compiler/lib/compilable-template.ts
  packages/@glimmer/opcode-compiler/lib/compiler.ts
  packages/@glimmer/opcode-compiler/lib/debug.ts
  packages/@glimmer/opcode-compiler/lib/wrapped-component.ts
  packages/@glimmer/program/lib/program.ts
  packages/@glimmer/runtime/lib/lifetime.ts
  packages/@glimmer/runtime/lib/opcodes.ts
  packages/@glimmer/runtime/lib/vm/append.ts
  packages/@glimmer/runtime/lib/vm/low-level.ts
  packages/@glimmer/runtime/lib/vm/stack.ts
  packages/@glimmer/syntax/lib/builders.ts
  packages/@glimmer/syntax/lib/traversal/traverse.ts
  packages/@glimmer/util/lib/lifetimes.ts
  packages/@glimmer/vm/lib/opcodes.toml
  test/index.html
  yarn.lock
Labels: internal

#1027 [BUGFIX] Fix immediate encoding
  packages/@glimmer/integration-tests/lib/suites/initial-render.ts
  packages/@glimmer/interfaces/lib/compile/instruction-encoder.d.ts
  packages/@glimmer/interfaces/lib/compile/operands.d.ts
  packages/@glimmer/low-level/lib/asm/stack.ts
  packages/@glimmer/opcode-compiler/lib/debug.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/encoder.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/vm.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/operands.ts
  packages/@glimmer/program/lib/program.ts
  packages/@glimmer/program/test/heap-test.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/vm.ts
  packages/@glimmer/runtime/lib/vm/stack.ts
  packages/@glimmer/util/index.ts
  packages/@glimmer/util/lib/immediate.ts
Labels: bug

#1037 interfaces: Remove unused imports
  packages/@glimmer/interfaces/lib/compile/encoder.d.ts
  packages/@glimmer/interfaces/lib/compile/operands.d.ts
  packages/@glimmer/interfaces/lib/compile/wire-format.d.ts
  packages/@glimmer/interfaces/lib/components/component-manager.d.ts
  packages/@glimmer/interfaces/lib/dom/tree-construction.d.ts
  packages/@glimmer/interfaces/lib/program.d.ts
  packages/@glimmer/interfaces/lib/runtime/environment.d.ts
  packages/@glimmer/interfaces/lib/runtime/runtime.d.ts
  packages/@glimmer/interfaces/lib/serialize.d.ts
Labels: internal

#1038 Replace imports from own package with relative imports
  packages/@glimmer/runtime/lib/compiled/opcodes/component.ts
  packages/@glimmer/syntax/test/generation/print-test.ts
Labels: internal

#1039 Add `.npmignore` files to each public package with a `test` folder
  packages/@glimmer/bundle-compiler/.npmignore
  packages/@glimmer/compiler/.npmignore
  packages/@glimmer/debug/.npmignore
  packages/@glimmer/dom-change-list/.npmignore
  packages/@glimmer/low-level/.npmignore
  packages/@glimmer/object-reference/.npmignore
  packages/@glimmer/object/.npmignore
  packages/@glimmer/opcode-compiler/.npmignore
  packages/@glimmer/program/.npmignore
  packages/@glimmer/reference/.npmignore
  packages/@glimmer/runtime/.npmignore
  packages/@glimmer/syntax/.npmignore
  packages/@glimmer/util/.npmignore
  packages/@glimmer/validator/.npmignore
Labels: internal

#1040 util: Promote `@glimmer/interfaces` to non-dev dependency
  packages/@glimmer/util/package.json
Labels: bug

#1041 runtime: Add missing `@glimmer/opcode-compiler` dependency
  packages/@glimmer/runtime/package.json
Labels: bug

#1042 ESLint: Enable `node/no-unpublished-import` rule
  .eslintrc.js
Labels: internal

#1045 integration-tests: Add missing `@glimmer/runtime` dependency
  packages/@glimmer/integration-tests/package.json
Labels: internal

#1044 Remove @glimmer/opcode-compiler dependency on @glimmer/runtime
  packages/@glimmer/interfaces/lib/program.d.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/context.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/components.ts
  packages/@glimmer/opcode-compiler/lib/syntax/builtins.ts
  packages/@glimmer/runtime/index.ts
  packages/@glimmer/runtime/lib/environment.ts
Labels: breaking

#1028 [CLEANUP][BREAKING] Simplifies JitRuntime, JitContext, Environment setup
  packages/@glimmer/integration-tests/lib/modes/jit/compilation-context.ts
  packages/@glimmer/integration-tests/lib/modes/jit/delegate.ts
  packages/@glimmer/integration-tests/lib/modes/jit/test-context.ts
  packages/@glimmer/integration-tests/test/partial-test.ts
  packages/@glimmer/reference/lib/iterable-impl.ts
  packages/@glimmer/runtime/index.ts
  packages/@glimmer/runtime/lib/environment.ts
Labels: breaking

#1046 [CLEANUP] Fix compiler typing
  packages/@glimmer/interfaces/lib/compile/wire-format.d.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/components.ts
  packages/@glimmer/opcode-compiler/lib/syntax/compilers.ts
  packages/@glimmer/opcode-compiler/lib/syntax/expressions.ts
  packages/@glimmer/opcode-compiler/lib/syntax/statements.ts
  packages/@glimmer/opcode-compiler/lib/wrapped-component.ts
Labels: internal

#1049 Enable eslint-plugin-node's no-extraneous-import rule (mostly).
  .eslintrc.js
  packages/@glimmer/debug/package.json
  packages/@glimmer/node/package.json
  packages/@glimmer/object-reference/package.json
  packages/@glimmer/program/test/heap-test.ts
  packages/@glimmer/reference/package.json
Labels: bug

#1053 Upgrade TypeScript version to 3.7.5
  package.json
  packages/@glimmer/program/test/heap-test.ts
  packages/@glimmer/reference/test/autotrack-test.ts
  yarn.lock
Labels: breaking

#984 Remove obsolete BREAKING.md file
  BREAKING.md
Labels: documentation
