Repository glimmerjs/glimmer-vm, pull requests merged in 2020-05, with the labels that each got.

#1086 [BUGFIX] Process in-element in compiler not parser
  packages/@glimmer/compiler/lib/template-compiler.ts
  packages/@glimmer/integration-tests/lib/compile.ts
  packages/@glimmer/integration-tests/lib/modes/aot/delegate.ts
  packages/@glimmer/integration-tests/lib/modes/jit/delegate.ts
  packages/@glimmer/integration-tests/lib/modes/jit/render.ts
  packages/@glimmer/integration-tests/lib/modes/rehydration/delegate.ts
  packages/@glimmer/integration-tests/lib/render-delegate.ts
  packages/@glimmer/integration-tests/lib/render-test.ts
  packages/@glimmer/integration-tests/lib/suites/in-element.ts
  packages/@glimmer/integration-tests/package.json
  packages/@glimmer/opcode-compiler/lib/syntax/builtins.ts
  packages/@glimmer/syntax/lib/parser/handlebars-node-visitors.ts
Labels: bug

#1089 Remove unused EPOCH tag
  packages/@glimmer/validator/index.ts
  packages/@glimmer/validator/lib/tracking.ts
Labels: breaking

#1088 [REFACTOR] Rename memoizeTracked to memo
  packages/@glimmer/validator/index.ts
  packages/@glimmer/validator/lib/tracking.ts
  packages/@glimmer/validator/test/tracking-test.ts
Labels: breaking

#1090 [FEATURE] Adds `cache` api
  packages/@glimmer/integration-tests/lib/render-test.ts
  packages/@glimmer/reference/lib/template.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/component.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/content.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/dom.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/vm.ts
  packages/@glimmer/validator/index.ts
  packages/@glimmer/validator/lib/tracked-data.ts
  packages/@glimmer/validator/lib/tracking.ts
  packages/@glimmer/validator/lib/validators.ts
  packages/@glimmer/validator/test/tracking-test.ts
Labels: breaking, enhancement

#1093 Update pinned yarn version to 1.22.4.
  package.json
Labels: internal

#1094 Update pinned Node version
  package.json
Labels: internal

#1095 Update release dependencies.
  package.json
  yarn.lock
Labels: internal

#1097 Remove bin/run-qunit.js test script.
  .travis.yml
  bin/run-qunit.js
  package.json
  yarn.lock
Labels: internal

#1096 Add GitHub Actions
  .github/workflows/ci.yml
Labels: internal

#1098 Remove .travis.yml
  .travis.yml
Labels: internal

#1099 Re-roll yarn.lock.
  yarn.lock
Labels: internal

#1102 Add a compile time error when passing arguments to regular HTML elements (e.g. `<a @foo=`)
  packages/@glimmer/compiler/lib/template-compiler.ts
  packages/@glimmer/compiler/test/compiler-test.ts
Labels: bug

#1103 [BUGFIX] Adds an assertion to prevent duplicate validator packages
  packages/@glimmer/validator/index.ts
  packages/@glimmer/validator/lib/utils.ts
Labels: bug
