Repository glimmerjs/glimmer-vm, pull requests merged in 2020-12, with the labels that each got.

#1223 [BUGFIX] Fix @glimmer/component
  packages/@glimmer/runtime/index.ts
Labels: bug

#1225 [FEAT] Implements Strict Mode
  packages/@glimmer/benchmark-env/src/benchmark/create-registry.ts
  packages/@glimmer/benchmark-env/src/benchmark/render-benchmark.ts
  packages/@glimmer/compiler/lib/compiler.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/context.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/index.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/keywords/append.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/keywords/block.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/keywords/call.ts
  packages/@glimmer/debug/lib/opcode-metadata.ts
  packages/@glimmer/integration-tests/index.ts
  packages/@glimmer/integration-tests/lib/compile.ts
  packages/@glimmer/integration-tests/lib/modes/jit/compilation-context.ts
  packages/@glimmer/integration-tests/lib/modes/jit/delegate.ts
  packages/@glimmer/integration-tests/lib/modes/rehydration/partial-rehydration-delegate.ts
  packages/@glimmer/integration-tests/lib/render-delegate.ts
  packages/@glimmer/integration-tests/lib/render-test.ts
  packages/@glimmer/integration-tests/lib/suites/entry-point.ts
  packages/@glimmer/integration-tests/lib/test-helpers/define.ts
  packages/@glimmer/integration-tests/lib/test-helpers/module.ts
  packages/@glimmer/integration-tests/lib/test-helpers/tracked-object.ts
  packages/@glimmer/integration-tests/test/strict-mode-test.ts
  packages/@glimmer/interfaces/lib/compile/encoder.d.ts
  packages/@glimmer/interfaces/lib/compile/operands.d.ts
  packages/@glimmer/interfaces/lib/compile/wire-format.d.ts
  packages/@glimmer/interfaces/lib/program.d.ts
  packages/@glimmer/interfaces/lib/serialize.d.ts
  packages/@glimmer/interfaces/lib/template.d.ts
  packages/@glimmer/interfaces/lib/vm-opcodes.d.ts
  packages/@glimmer/manager/index.ts
  packages/@glimmer/manager/lib/internal/index.ts
  packages/@glimmer/manager/lib/public/index.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/encoder.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/components.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/resolution.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/shared.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/stdlib.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/operands.ts
  packages/@glimmer/opcode-compiler/lib/syntax/expressions.ts
  packages/@glimmer/opcode-compiler/lib/syntax/statements.ts
  packages/@glimmer/opcode-compiler/lib/template.ts
  packages/@glimmer/program/lib/constants.ts
  packages/@glimmer/program/lib/util/default-template.ts
  packages/@glimmer/runtime/index.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/-debug-strip.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/component.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/content.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/vm.ts
  packages/@glimmer/runtime/lib/dom/normalize.ts
  packages/@glimmer/runtime/lib/references/curry-component.ts
  packages/@glimmer/runtime/lib/render.ts
  packages/@glimmer/syntax/lib/symbol-table.ts
  packages/@glimmer/syntax/lib/v2-a/normalize.ts
  packages/@glimmer/vm/lib/opcodes.toml
Labels: breaking

#1232 [REFACTOR] Make Owner VM state
  packages/@glimmer/benchmark-env/src/benchmark/basic-component-manager.ts
  packages/@glimmer/benchmark-env/src/benchmark/create-env-delegate.ts
  packages/@glimmer/integration-tests/lib/components/emberish-curly.ts
  packages/@glimmer/integration-tests/lib/modes/env.ts
  packages/@glimmer/integration-tests/lib/modes/jit/register.ts
  packages/@glimmer/integration-tests/lib/modes/jit/render.ts
  packages/@glimmer/integration-tests/test/env-test.ts
  packages/@glimmer/integration-tests/test/owner-test.ts
  packages/@glimmer/interfaces/lib/compile/operands.d.ts
  packages/@glimmer/interfaces/lib/managers/internal/component.d.ts
  packages/@glimmer/interfaces/lib/runtime/environment.d.ts
  packages/@glimmer/interfaces/lib/runtime/scope.d.ts
  packages/@glimmer/interfaces/lib/runtime/vm.d.ts
  packages/@glimmer/manager/lib/public/component.ts
  packages/@glimmer/manager/lib/util/capabilities.ts
  packages/@glimmer/manager/test/capabilities-test.ts
  packages/@glimmer/manager/test/managers-test.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/delegate.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/encoder.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/components.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/operands.ts
  packages/@glimmer/opcode-compiler/lib/syntax/statements.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/component.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/expressions.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/partial.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/vm.ts
  packages/@glimmer/runtime/lib/component/curried-component.ts
  packages/@glimmer/runtime/lib/component/template-only.ts
  packages/@glimmer/runtime/lib/environment.ts
  packages/@glimmer/runtime/lib/references/curry-component.ts
  packages/@glimmer/runtime/lib/render.ts
  packages/@glimmer/runtime/lib/scope.ts
  packages/@glimmer/runtime/lib/vm/append.ts
Labels: breaking

#1235 [FEATURE] Adds dynamic curly components and helpers
  packages/@glimmer/compiler/lib/passes/1-normalization/keywords/append.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/keywords/call.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/utils/is-node.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/visitors/element/classified.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/visitors/expressions.ts
  packages/@glimmer/compiler/lib/passes/2-encoding/expressions.ts
  packages/@glimmer/compiler/lib/passes/2-encoding/mir.ts
  packages/@glimmer/compiler/lib/wire-format-debug.ts
  packages/@glimmer/debug/lib/opcode-metadata.ts
  packages/@glimmer/integration-tests/lib/suites/components.ts
  packages/@glimmer/integration-tests/test/helpers/dynamic-helpers-test.ts
  packages/@glimmer/integration-tests/test/strict-mode-test.ts
  packages/@glimmer/interfaces/lib/compile/operands.d.ts
  packages/@glimmer/interfaces/lib/compile/wire-format.d.ts
  packages/@glimmer/interfaces/lib/content.d.ts
  packages/@glimmer/interfaces/lib/managers/internal/helper.d.ts
  packages/@glimmer/interfaces/lib/template.d.ts
  packages/@glimmer/interfaces/lib/vm-opcodes.d.ts
  packages/@glimmer/manager/lib/public/helper.ts
  packages/@glimmer/manager/lib/public/index.ts
  packages/@glimmer/manager/test/managers-test.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/components.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/conditional.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/shared.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/stdlib.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/vm.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/operands.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/stdlib.ts
  packages/@glimmer/opcode-compiler/lib/syntax/expressions.ts
  packages/@glimmer/opcode-compiler/lib/syntax/statements.ts
  packages/@glimmer/program/lib/constants.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/component.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/content.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/expressions.ts
  packages/@glimmer/runtime/lib/helpers/curried-helper.ts
  packages/@glimmer/runtime/lib/references/curry-component.ts
  packages/@glimmer/runtime/lib/references/curry-helper.ts
  packages/@glimmer/syntax/lib/v2-a/loose-resolution.ts
  packages/@glimmer/vm/lib/opcodes.toml
Labels: breaking

#1240 [FEATURE] Adds inline if and unless keywords
  packages/@glimmer/compiler/lib/passes/1-normalization/keywords/append.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/keywords/block.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/keywords/call.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/keywords/utils/if-unless.ts
  packages/@glimmer/compiler/lib/passes/2-encoding/content.ts
  packages/@glimmer/compiler/lib/passes/2-encoding/expressions.ts
  packages/@glimmer/compiler/lib/passes/2-encoding/mir.ts
  packages/@glimmer/compiler/lib/wire-format-debug.ts
  packages/@glimmer/debug/lib/opcode-metadata.ts
  packages/@glimmer/integration-tests/test/syntax/if-unless-test.ts
  packages/@glimmer/integration-tests/test/updating-test.ts
  packages/@glimmer/interfaces/lib/compile/wire-format.d.ts
  packages/@glimmer/interfaces/lib/vm-opcodes.d.ts
  packages/@glimmer/opcode-compiler/lib/syntax/expressions.ts
  packages/@glimmer/opcode-compiler/lib/syntax/statements.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/expressions.ts
  packages/@glimmer/vm/lib/opcodes.toml
Labels: enhancement

#1242 [REFACTOR] Make `-get-dynamic-var` a keyword
  packages/@glimmer/compiler/lib/passes/1-normalization/keywords/append.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/keywords/call.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/keywords/utils/dynamic-vars.ts
  packages/@glimmer/compiler/lib/passes/2-encoding/expressions.ts
  packages/@glimmer/compiler/lib/passes/2-encoding/mir.ts
  packages/@glimmer/compiler/lib/wire-format-debug.ts
  packages/@glimmer/integration-tests/lib/modes/jit/delegate.ts
  packages/@glimmer/interfaces/lib/compile/wire-format.d.ts
  packages/@glimmer/interfaces/lib/vm-opcodes.d.ts
  packages/@glimmer/opcode-compiler/lib/syntax/expressions.ts
  packages/@glimmer/runtime/index.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/expressions.ts
  packages/@glimmer/runtime/lib/helpers/get-dynamic-var.ts
Labels: enhancement

#1241 Fix missing component error message
  packages/@glimmer/runtime/lib/references/curry-value.ts
Labels: bug

#1249 Add test for usage of `{{@component.foo}}`
  packages/@glimmer/compiler/lib/passes/1-normalization/keywords/impl.ts
  packages/@glimmer/integration-tests/test/ember-component-test.ts
  packages/@glimmer/integration-tests/test/strict-mode-test.ts
Labels: internal

#1248 Update automated release tooling
  RELEASE.md
  package.json
  yarn.lock
Labels: internal
