Repository glimmerjs/glimmer-vm, pull requests merged in 2020-10, with the labels that each got.

#1172 Ensure "pause on uncaught" exceptions pauses in correct location.
  packages/@glimmer/runtime/lib/vm/append.ts
  packages/@glimmer/runtime/lib/vm/update.ts
Labels: bug

#1174 Update simple-html-tokenizer and use its codemod mode.
  package.json
  packages/@glimmer/integration-tests/package.json
  packages/@glimmer/syntax/lib/parser.ts
  packages/@glimmer/syntax/lib/parser/tokenizer-event-handlers.ts
  packages/@glimmer/syntax/package.json
  yarn.lock
Labels: bug

#1175 Add `yarn lint` script and stop aliasing `yarn eslint`.
  .github/workflows/ci.yml
  package.json
  yarn.lock
Labels: internal

#1184 [REFACTOR] Upstream `setComponentTemplate`
  packages/@glimmer/benchmark-env/src/benchmark/create-registry.ts
  packages/@glimmer/integration-tests/lib/compile.ts
  packages/@glimmer/integration-tests/lib/components/emberish-curly.ts
  packages/@glimmer/integration-tests/lib/components/emberish-glimmer.ts
  packages/@glimmer/integration-tests/lib/components/template-only.ts
  packages/@glimmer/integration-tests/lib/components/test-component.ts
  packages/@glimmer/integration-tests/lib/components/types.ts
  packages/@glimmer/integration-tests/lib/locator.ts
  packages/@glimmer/integration-tests/lib/modes/jit/compilation-context.ts
  packages/@glimmer/integration-tests/lib/modes/jit/delegate.ts
  packages/@glimmer/integration-tests/lib/modes/jit/register.ts
  packages/@glimmer/integration-tests/lib/modes/jit/registry.ts
  packages/@glimmer/integration-tests/lib/modes/jit/resolver.ts
  packages/@glimmer/integration-tests/test/ember-component-test.ts
  packages/@glimmer/integration-tests/test/partial-test.ts
  packages/@glimmer/interfaces/lib/components.d.ts
  packages/@glimmer/interfaces/lib/components/component-manager.d.ts
  packages/@glimmer/interfaces/lib/serialize.d.ts
  packages/@glimmer/interfaces/lib/template.d.ts
  packages/@glimmer/runtime/index.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/component.ts
  packages/@glimmer/runtime/lib/template.ts
Labels: breaking
