Repository glimmerjs/glimmer-vm, pull requests merged in 2020-01, with the labels that each got.

#835 Refactor printer
  packages/@glimmer/syntax/lib/generation/print.ts
  packages/@glimmer/syntax/lib/generation/printer.ts
  packages/@glimmer/syntax/lib/types/nodes.ts
  packages/@glimmer/syntax/test/generation/print-test.ts
Labels: bug

#995 ESLint: Add `node` plugin
  .eslintrc.js
  .npmignore
  build/debug.js
  build/symlink-dependencies/index.js
  build/symlink-dependencies/package.json
  package.json
  packages/@glimmer/reference/test/autotrack-test.ts
  packages/@glimmer/syntax/handlebars-shim.js
  packages/@glimmer/syntax/lib/builders.ts
  yarn.lock
Labels: internal

#985 syntax: Add optional `path` argument to visitor functions
  packages/@glimmer/syntax/index.ts
  packages/@glimmer/syntax/lib/traversal/path.ts
  packages/@glimmer/syntax/lib/traversal/traverse.ts
  packages/@glimmer/syntax/lib/traversal/visitor.ts
  packages/@glimmer/syntax/test/traversal/visiting-node-test.ts
Labels: enhancement

#996 Update run-types-test.js to use local `tsc`.
  bin/run-types-tests.js
Labels: internal

#997 ESLint: Add `qunit` plugin
  .eslintrc.js
  package.json
  packages/@glimmer/compiler/test/compiler-test.ts
  packages/@glimmer/integration-tests/test/compiler/compile-options-test.ts
  packages/@glimmer/object/test/ember-create-test.ts
  packages/@glimmer/object/test/ember-metal-concatenated-properties-test.ts
  packages/@glimmer/syntax/test/traversal/visiting-node-test.ts
  yarn.lock
Labels: internal

#998 ESLint: Enable `node/no-missing-import` rule
  .eslintrc.js
Labels: internal

#1000 Add missing `@simple-dom` dependencies
  packages/@glimmer/compiler/package.json
  packages/@glimmer/debug/package.json
  packages/@glimmer/dom-change-list/package.json
  packages/@glimmer/integration-tests/package.json
  packages/@glimmer/interfaces/package.json
  packages/@glimmer/node/package.json
  packages/@glimmer/runtime/package.json
  packages/@glimmer/util/package.json
Labels: internal

#1001 Remove outdated `typescript` dev dependencies
  packages/@glimmer/bundle-compiler/package.json
  packages/@glimmer/compiler/package.json
  packages/@glimmer/debug/package.json
  packages/@glimmer/dom-change-list/package.json
  packages/@glimmer/encoder/package.json
  packages/@glimmer/integration-tests/package.json
  packages/@glimmer/interfaces/package.json
  packages/@glimmer/low-level/package.json
  packages/@glimmer/node/package.json
  packages/@glimmer/object-reference/package.json
  packages/@glimmer/object/package.json
  packages/@glimmer/opcode-compiler/package.json
  packages/@glimmer/program/package.json
  packages/@glimmer/reference/package.json
  packages/@glimmer/runtime/package.json
  packages/@glimmer/syntax/package.json
  packages/@glimmer/util/package.json
  packages/@glimmer/validator/package.json
  packages/@glimmer/vm/package.json
  packages/@glimmer/wire-format/package.json
Labels: internal

#1002 Use Yarn workspaces
  .eslintrc.js
  package.json
  yarn.lock
Labels: internal

#1003 Use type signatures from `@types/qunit` and `qunit` instead of local copy
  packages/@glimmer/dom-change-list/package.json
  packages/@glimmer/dom-change-list/test/interfaces.ts
  packages/@glimmer/dom-change-list/test/test-case.ts
  packages/@glimmer/integration-tests/test/updating-test.ts
Labels: internal

#1004 syntax/test/plugin-node: Replace relative imports with package imports
  packages/@glimmer/syntax/test/plugin-node-test.ts
Labels: internal

#1009 [BUGFIX] Don't serialize template metas in the JIT constant pool
  packages/@glimmer/integration-tests/lib/modes/jit/compilation-context.ts
  packages/@glimmer/opcode-compiler/lib/program-context.ts
  packages/@glimmer/opcode-compiler/test/jit-context-test.ts
  packages/@glimmer/program/lib/constants.ts
  packages/@glimmer/runtime/lib/environment.ts
Labels: breaking
