Repository glimmerjs/glimmer-vm, pull requests merged in 2020-07, with the labels that each got.

#1114 [REFACTOR] Remove LinkedList and simplify iteration
  packages/@glimmer/integration-tests/lib/suites/each.ts
  packages/@glimmer/interfaces/index.d.ts
  packages/@glimmer/interfaces/lib/dom/attributes.d.ts
  packages/@glimmer/interfaces/lib/list.d.ts
  packages/@glimmer/interfaces/lib/runtime/environment.d.ts
  packages/@glimmer/reference/index.ts
  packages/@glimmer/reference/lib/iterable-impl.ts
  packages/@glimmer/reference/lib/iterable.ts
  packages/@glimmer/reference/lib/template.ts
  packages/@glimmer/reference/test/iterable-impl-test.ts
  packages/@glimmer/reference/test/iterable-test.ts
  packages/@glimmer/reference/test/utils/iterator.ts
  packages/@glimmer/reference/test/utils/reference.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/lists.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/vm.ts
  packages/@glimmer/runtime/lib/environment.ts
  packages/@glimmer/runtime/lib/opcodes.ts
  packages/@glimmer/runtime/lib/utils/tags.ts
  packages/@glimmer/runtime/lib/vm/append.ts
  packages/@glimmer/runtime/lib/vm/element-builder.ts
  packages/@glimmer/runtime/lib/vm/render-result.ts
  packages/@glimmer/runtime/lib/vm/update.ts
  packages/@glimmer/util/index.ts
  packages/@glimmer/util/lib/debug-steps.ts
  packages/@glimmer/util/lib/list-utils.ts
Labels: breaking

#1119 Ensure `isDestroying`/`isDestroyed` without children or destructors does not fail `assertDestroyablesDestroyed`
  packages/@glimmer/runtime/lib/destroyables.ts
  packages/@glimmer/runtime/test/destroyables-test.ts
Labels: bug

#1121 Expose the destroyables on the error thrown by `assertDestroyablesDestroyed`
  packages/@glimmer/runtime/lib/destroyables.ts
  packages/@glimmer/runtime/test/destroyables-test.ts
Labels: enhancement

#1122 [Refactor] Use a map to dedupe constants instead of indexOf
  packages/@glimmer/bundle-compiler/lib/debug-constants.ts
  packages/@glimmer/integration-tests/lib/suites/bundle-compiler.ts
  packages/@glimmer/interfaces/lib/program.d.ts
  packages/@glimmer/program/lib/constants.ts
  packages/@glimmer/runtime/lib/vm/arguments.ts
Labels: enhancement
