Repository glimmerjs/glimmer-vm, pull requests merged in 2021-03, with the labels that each got.

#1285 Pin @handlebars/parser to 2.0.x.
  package.json
  packages/@glimmer/syntax/package.json
  yarn.lock
Labels: internal

#1284 Ensure Entities are never transformed in codemod mode.
  packages/@glimmer/syntax/lib/parser/tokenizer-event-handlers.ts
  packages/@glimmer/syntax/test/generation/print-test.ts
Labels: bug

#1276 [BUGFIX] Do not eagerly consume modifier args during destruction
  packages/@glimmer/integration-tests/test/managers/modifier-manager-test.ts
  packages/@glimmer/manager/lib/public/modifier.ts
Labels: bug

#1290 Fixes VM Babel plugin generation in browsers
  packages/build-utils/@glimmer/vm-babel-plugins/index.js
Labels: enhancement
