Repository glimmerjs/glimmer-vm, pull requests merged in 2021-01, with the labels that each got.

#1253 [BUGFIX] Convert component names after symbol allocation
  packages/@glimmer/integration-tests/test/compiler/compile-options-test.ts
  packages/@glimmer/syntax/lib/symbol-table.ts
  packages/@glimmer/syntax/lib/v1/parser-builders.ts
  packages/@glimmer/syntax/lib/v2-a/normalize.ts
Labels: bug

#1257 Add `assert` and `deprecate` to global context API
  .eslintignore
  .eslintrc.json
  .github/workflows/ci.yml
  package.json
  packages/@glimmer/benchmark-env/src/benchmark/create-env-delegate.ts
  packages/@glimmer/global-context/index.ts
  packages/@glimmer/integration-tests/lib/modes/env.ts
  packages/@glimmer/validator/lib/debug.ts
  packages/build-utils/@glimmer/vm-babel-plugins/README.md
  packages/build-utils/@glimmer/vm-babel-plugins/index.js
  packages/build-utils/@glimmer/vm-babel-plugins/package.json
  packages/build-utils/@glimmer/vm-babel-plugins/test/fixtures/basic/.babelrc.js
  packages/build-utils/@glimmer/vm-babel-plugins/test/fixtures/basic/code.js
  packages/build-utils/@glimmer/vm-babel-plugins/test/fixtures/basic/output.js
  packages/build-utils/@glimmer/vm-babel-plugins/test/fixtures/explicit-false/.babelrc.js
  packages/build-utils/@glimmer/vm-babel-plugins/test/fixtures/explicit-false/code.js
  packages/build-utils/@glimmer/vm-babel-plugins/test/fixtures/explicit-false/output.js
  packages/build-utils/@glimmer/vm-babel-plugins/test/fixtures/explicit-true/.babelrc.js
  packages/build-utils/@glimmer/vm-babel-plugins/test/fixtures/explicit-true/code.js
  packages/build-utils/@glimmer/vm-babel-plugins/test/fixtures/explicit-true/output.js
  packages/build-utils/@glimmer/vm-babel-plugins/test/index.js
  yarn.lock
Labels: breaking

#1258 Remove usages of `this.property` fallback from tests
  packages/@glimmer/integration-tests/lib/render-test.ts
  packages/@glimmer/integration-tests/lib/suites/components.ts
  packages/@glimmer/integration-tests/lib/suites/custom-dom-helper.ts
  packages/@glimmer/integration-tests/lib/suites/debugger.ts
  packages/@glimmer/integration-tests/lib/suites/each.ts
  packages/@glimmer/integration-tests/lib/suites/emberish-components.ts
  packages/@glimmer/integration-tests/lib/suites/in-element.ts
  packages/@glimmer/integration-tests/lib/suites/initial-render.ts
  packages/@glimmer/integration-tests/lib/suites/shadowing.ts
  packages/@glimmer/integration-tests/lib/suites/ssr.ts
  packages/@glimmer/integration-tests/lib/suites/with-dynamic-vars.ts
  packages/@glimmer/integration-tests/lib/suites/yield.ts
  packages/@glimmer/integration-tests/test/attributes-test.ts
  packages/@glimmer/integration-tests/test/chaos-rehydration-test.ts
  packages/@glimmer/integration-tests/test/ember-component-test.ts
  packages/@glimmer/integration-tests/test/helpers/array-test.ts
  packages/@glimmer/integration-tests/test/helpers/get-test.ts
  packages/@glimmer/integration-tests/test/initial-render-test.ts
  packages/@glimmer/integration-tests/test/input-range-test.ts
  packages/@glimmer/integration-tests/test/invocation-generation-test.ts
  packages/@glimmer/integration-tests/test/keywords/log-test.ts
  packages/@glimmer/integration-tests/test/modifiers-test.ts
  packages/@glimmer/integration-tests/test/modifiers/on-test.ts
  packages/@glimmer/integration-tests/test/partial-test.ts
  packages/@glimmer/integration-tests/test/style-warnings-test.ts
  packages/@glimmer/integration-tests/test/updating-content-matrix-test.ts
  packages/@glimmer/integration-tests/test/updating-modifiers-test.ts
  packages/@glimmer/integration-tests/test/updating-svg-test.ts
  packages/@glimmer/integration-tests/test/updating-test.ts
  packages/@glimmer/syntax/test/traversal/visiting-node-test.ts
Labels: internal

#1255 Don't call `customizeComponentName` on curly components
  packages/@glimmer/integration-tests/test/compiler/compile-options-test.ts
  packages/@glimmer/syntax/lib/symbol-table.ts
  packages/@glimmer/syntax/lib/utils.ts
  packages/@glimmer/syntax/lib/v2-a/loose-resolution.ts
  packages/@glimmer/syntax/lib/v2-a/normalize.ts
  packages/@glimmer/syntax/lib/v2-a/objects/resolution.ts
Labels: bug
