Repository glimmerjs/glimmer-vm, pull requests merged in 2021-02, with the labels that each got.

#1259 Adds deprecation for property fallback lookup
  packages/@glimmer/integration-tests/lib/modes/env.ts
  packages/@glimmer/integration-tests/test/ember-component-test.ts
  packages/@glimmer/integration-tests/test/helpers/dynamic-helpers-test.ts
  packages/@glimmer/integration-tests/test/updating-test.ts
  packages/@glimmer/interfaces/lib/compile/encoder.d.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/encoder.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/resolution.ts
  packages/@glimmer/opcode-compiler/lib/syntax/expressions.ts
  packages/@glimmer/opcode-compiler/lib/syntax/statements.ts
  packages/@glimmer/validator/test/tracking-test.ts
Labels: enhancement

#1260 Omit scope property from precompiled templates in loose mode
  packages/@glimmer/compiler/lib/compiler.ts
  packages/@glimmer/interfaces/lib/compile/wire-format.d.ts
  packages/@glimmer/interfaces/lib/template.d.ts
Labels: bug

#1263 [BUGFIX] Ensure owner is available during resolution for all components
  packages/@glimmer/integration-tests/test/owner-test.ts
  packages/@glimmer/interfaces/lib/program.d.ts
  packages/@glimmer/opcode-compiler/lib/opcode-builder/helpers/resolution.ts
  packages/@glimmer/program/lib/constants.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/component.ts
  packages/@glimmer/runtime/lib/render.ts
Labels: breaking

#1266 Maintain relative order of attributes and comments within an `ElementNode`
  packages/@glimmer/syntax/index.ts
  packages/@glimmer/syntax/lib/generation/printer.ts
  packages/@glimmer/syntax/lib/generation/util.ts
  packages/@glimmer/syntax/lib/parser/handlebars-node-visitors.ts
  packages/@glimmer/syntax/test/generation/print-test.ts
  packages/@glimmer/syntax/test/parser-node-test.ts
Labels: bug

#1269 [BUGFIX] Fix {{get}} when used on non-objects
  packages/@glimmer/integration-tests/lib/modes/env.ts
  packages/@glimmer/integration-tests/test/helpers/get-test.ts
  packages/@glimmer/runtime/lib/helpers/get.ts
Labels: bug

#1268 [BUGFIX] Fix reactivity of dynamic attributes
  packages/@glimmer/integration-tests/test/attributes-test.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/component.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/dom.ts
Labels: bug

#1270 Ensure inline `if` returns `undefined` when no falsey value is provided
  packages/@glimmer/compiler/lib/passes/2-encoding/expressions.ts
  packages/@glimmer/integration-tests/test/updating-test.ts
  packages/@glimmer/interfaces/lib/compile/wire-format.d.ts
Labels: bug

#1272 [BUGFIX] Fix reactivity of dynamic attributes
  packages/@glimmer/integration-tests/test/attributes-test.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/component.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/dom.ts
Labels: bug

#1271 Upstream modifier tests
  packages/@glimmer/integration-tests/lib/test-helpers/define.ts
  packages/@glimmer/integration-tests/test/managers/modifier-manager-test.ts
  packages/@glimmer/interfaces/lib/managers/modifier.d.ts
  packages/@glimmer/manager/lib/public/modifier.ts
Labels: internal

#1267 [BUGFIX] Fixes dynamic helpers and modifiers with updating definitions
  packages/@glimmer/benchmark-env/src/benchmark/if-helper.ts
  packages/@glimmer/benchmark-env/src/benchmark/on-modifier.ts
  packages/@glimmer/benchmark-env/src/create-benchmark.ts
  packages/@glimmer/compiler/lib/passes/1-normalization/keywords/impl.ts
  packages/@glimmer/destroyable/index.ts
  packages/@glimmer/integration-tests/lib/modes/jit/register.ts
  packages/@glimmer/integration-tests/lib/modifiers.ts
  packages/@glimmer/integration-tests/lib/test-helpers/define.ts
  packages/@glimmer/integration-tests/test/helpers/fn-test.ts
  packages/@glimmer/integration-tests/test/managers/helper-manager-test.ts
  packages/@glimmer/integration-tests/test/strict-mode-test.ts
  packages/@glimmer/integration-tests/test/updating-test.ts
  packages/@glimmer/interfaces/lib/managers/internal/modifier.d.ts
  packages/@glimmer/interfaces/lib/runtime/helper.d.ts
  packages/@glimmer/manager/lib/public/helper.ts
  packages/@glimmer/manager/lib/public/modifier.ts
  packages/@glimmer/manager/test/managers-test.ts
  packages/@glimmer/reference/lib/iterable.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/component.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/content.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/dom.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/expressions.ts
  packages/@glimmer/runtime/lib/curried-value.ts
  packages/@glimmer/runtime/lib/helpers/array.ts
  packages/@glimmer/runtime/lib/helpers/concat.ts
  packages/@glimmer/runtime/lib/helpers/fn.ts
  packages/@glimmer/runtime/lib/helpers/get.ts
  packages/@glimmer/runtime/lib/helpers/hash.ts
  packages/@glimmer/runtime/lib/modifiers/on.ts
  packages/@glimmer/runtime/lib/references/curry-value.ts
  packages/@glimmer/runtime/lib/vm/arguments.ts
  packages/@glimmer/util/lib/collections.ts
Labels: breaking

#1273 [BUGFIX] Use built-in Object.assign if possible
  packages/@glimmer/util/lib/object-utils.ts
  test/index.html
Labels: bug
