Repository glimmerjs/glimmer-vm, pull requests merged in 2023-11, with the labels that each got.

#1481 MakePrimitiveRef generic so that UNDEFINED_REFERENCE can be Reference<undefined> rather than Reference<unknown>
  packages/@glimmer/reference/lib/reference.ts
Labels: bug

#1485 Remove dependency on @glimmer/low-level because it doesn't exist anymore (and is unused)
  packages/@glimmer/runtime/package.json
  pnpm-lock.yaml
Labels: bug

#1482 Setup the cache server
  .github/workflows/ci.yml
  bin/run-types-tests.mjs
  package.json
  packages/@glimmer/compiler/package.json
  packages/@glimmer/debug/package.json
  packages/@glimmer/destroyable/package.json
  packages/@glimmer/dom-change-list/package.json
  packages/@glimmer/encoder/package.json
  packages/@glimmer/global-context/package.json
  packages/@glimmer/interfaces/package.json
  packages/@glimmer/manager/package.json
  packages/@glimmer/node/package.json
  packages/@glimmer/opcode-compiler/package.json
  packages/@glimmer/owner/package.json
  packages/@glimmer/program/package.json
  packages/@glimmer/reference/package.json
  packages/@glimmer/runtime/package.json
  packages/@glimmer/syntax/package.json
  packages/@glimmer/util/package.json
  packages/@glimmer/validator/package.json
  packages/@glimmer/vm-babel-plugins/package.json
  packages/@glimmer/vm/package.json
  packages/@glimmer/wire-format/package.json
  pnpm-lock.yaml
  tsconfig.dist.json
  turbo.json
Labels: internal

#1460 fix capture render tree fails when errors in args
  packages/@glimmer-workspace/integration-tests/test/debug-render-tree-test.ts
  packages/@glimmer/interfaces/lib/runtime/arguments.d.ts
  packages/@glimmer/interfaces/lib/runtime/debug-render-tree.d.ts
  packages/@glimmer/runtime/lib/debug-render-tree.ts
  packages/@glimmer/runtime/lib/vm/arguments.ts
  packages/@glimmer/vm-babel-plugins/index.ts
Labels: bug

#1486 Remove @glimmer/dom-change-list as nothing depends on it
  packages/@glimmer/.eslintrc.cjs
  packages/@glimmer/dom-change-list/.npmignore
  packages/@glimmer/dom-change-list/index.ts
  packages/@glimmer/dom-change-list/lib/dom-operations.ts
  packages/@glimmer/dom-change-list/lib/node-tokens.ts
  packages/@glimmer/dom-change-list/lib/tree-builder.ts
  packages/@glimmer/dom-change-list/lib/tree-construction.ts
  packages/@glimmer/dom-change-list/package.json
  packages/@glimmer/dom-change-list/rollup.config.mjs
  packages/@glimmer/dom-change-list/test/change-list-test.ts
  packages/@glimmer/dom-change-list/test/package.json
  packages/@glimmer/dom-change-list/test/support.ts
  packages/@glimmer/dom-change-list/test/test-case.ts
  packages/@glimmer/dom-change-list/test/tree-builder-test.ts
Labels: breaking

#1488 Add back package.json#module so the ember build can have fewer changes
  packages/@glimmer/compiler/package.json
  packages/@glimmer/debug/package.json
  packages/@glimmer/destroyable/package.json
  packages/@glimmer/encoder/package.json
  packages/@glimmer/global-context/package.json
  packages/@glimmer/interfaces/package.json
  packages/@glimmer/manager/package.json
  packages/@glimmer/node/package.json
  packages/@glimmer/opcode-compiler/package.json
  packages/@glimmer/owner/package.json
  packages/@glimmer/program/package.json
  packages/@glimmer/reference/package.json
  packages/@glimmer/runtime/package.json
  packages/@glimmer/syntax/package.json
  packages/@glimmer/util/package.json
  packages/@glimmer/validator/package.json
  packages/@glimmer/vm-babel-plugins/package.json
  packages/@glimmer/vm/package.json
  packages/@glimmer/wire-format/package.json
Labels: bug

#1494 Compile away local debug for publish
  packages/@glimmer-workspace/build/lib/config.js
  packages/@glimmer-workspace/build/lib/import-meta.js
  packages/@glimmer/local-debug-flags/index.ts
Labels: internal

#1483 Use stricter type for createPrimitiveRef
  packages/@glimmer/reference/lib/reference.ts
Labels: internal

#1506 Sort package.json files to reduce diff from the Error Recovery PR
  .eslintrc.cjs
  benchmark/benchmarks/krausest/package.json
  bin/package.json
  package.json
  packages/@glimmer-workspace/benchmark-env/package.json
  packages/@glimmer-workspace/build/package.json
  packages/@glimmer-workspace/integration-tests/package.json
  packages/@glimmer-workspace/test-utils/package.json
  packages/@glimmer/compiler/package.json
  packages/@glimmer/debug/package.json
  packages/@glimmer/destroyable/package.json
  packages/@glimmer/encoder/package.json
  packages/@glimmer/global-context/package.json
  packages/@glimmer/interfaces/package.json
  packages/@glimmer/local-debug-flags/package.json
  packages/@glimmer/manager/package.json
  packages/@glimmer/node/package.json
  packages/@glimmer/opcode-compiler/package.json
  packages/@glimmer/owner/package.json
  packages/@glimmer/program/package.json
  packages/@glimmer/reference/package.json
  packages/@glimmer/runtime/package.json
  packages/@glimmer/syntax/package.json
  packages/@glimmer/util/package.json
  packages/@glimmer/validator/package.json
  packages/@glimmer/vm-babel-plugins/package.json
  packages/@glimmer/vm/package.json
  packages/@glimmer/wire-format/package.json
  pnpm-lock.yaml
Labels: internal

#1495 make it run on windows
  bin/run-types-tests.mjs
  packages/@glimmer-workspace/build/lib/config.js
Labels: internal
