Repository glimmerjs/glimmer-vm, pull requests merged in 2023-12, with the labels that each got.

#1516 fix `exports` config for @glimmer/destroyable and @glimmer/debug
  packages/@glimmer/debug/package.json
  packages/@glimmer/destroyable/package.json
Labels: bug

#1523 Restore a working linking setup
  .eslintignore
  .gitignore
  benchmark/tsconfig.json
  bin/link-all.mts
  bin/package.json
  bin/unlink-all.mts
  bin/yalc-publish.mts
  glimmer-vm.code-workspace
  lib/local-linker/index.js
  lib/local-linker/package.json
  lib/tsconfig.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tsconfig.json
Labels: internal

#1440 Fix helper/modifier memory leak
  packages/@glimmer/runtime/lib/compiled/opcodes/dom.ts
  packages/@glimmer/runtime/lib/compiled/opcodes/expressions.ts
Labels: bug

#1520 [perf] replace Math.max usage with reduce and pure compare
  packages/@glimmer/validator/lib/validators.ts
Labels: enhancement

#1530 Upgrade to vite 5
  benchmark/benchmarks/krausest/package.json
  package.json
  packages/@glimmer-workspace/build/package.json
  packages/package.json
  pnpm-lock.yaml
Labels: internal

#1538 Make feature discovery lazy
  packages/@glimmer/runtime/lib/dom/sanitized-values.ts
Labels: bug

#1537 adjust benchmark close to real-life usage
  .github/workflows/perf.yml
  benchmark/benchmarks/krausest/lib/components/Application.hbs
  benchmark/benchmarks/krausest/lib/components/Application.ts
  benchmark/benchmarks/krausest/lib/components/Row.hbs
  benchmark/benchmarks/krausest/lib/components/Row.ts
  benchmark/benchmarks/krausest/lib/index.ts
  benchmark/benchmarks/krausest/lib/utils/compat.ts
  benchmark/benchmarks/krausest/lib/utils/data.ts
  benchmark/benchmarks/krausest/tsconfig.json
  benchmark/benchmarks/krausest/vite.config.mts
  bin/setup-bench.mjs
Labels: internal

#1543 Fix @glimmer/destroyable dev exports
  packages/@glimmer/destroyable/package.json
Labels: bug
