Repository glimmerjs/glimmer-vm, pull requests merged in 2024-11, with the labels that each got.

#1648 Improve benchmark setup, consistently rely on publishConfig
  .github/workflows/perf.yml
  .gitignore
  bin/published-packages.mts
  bin/setup-bench.mjs
  bin/tsconfig.json
  packages/@glimmer-workspace/benchmark-env/package.json
  packages/@glimmer-workspace/integration-tests/test/chaos-rehydration-test.ts
  packages/@glimmer/compiler/package.json
  packages/@glimmer/debug-util/package.json
  packages/@glimmer/debug/package.json
  packages/@glimmer/destroyable/package.json
  packages/@glimmer/encoder/package.json
  packages/@glimmer/global-context/package.json
  packages/@glimmer/interfaces/package.json
  packages/@glimmer/local-debug-babel-plugin/package.json
  packages/@glimmer/local-debug-flags/package.json
  packages/@glimmer/manager/package.json
  packages/@glimmer/node/package.json
  packages/@glimmer/opcode-compiler/package.json
  packages/@glimmer/owner/package.json
  packages/@glimmer/program/package.json
  packages/@glimmer/reference/package.json
  packages/@glimmer/runtime/package.json
  packages/@glimmer/syntax/package.json
  packages/@glimmer/util/package.json
  packages/@glimmer/validator/package.json
  packages/@glimmer/vm-babel-plugins/package.json
  packages/@glimmer/vm/package.json
  packages/@glimmer/wire-format/package.json
Labels: perf

#1653 Fix perf bench comment
  bin/setup-bench.mjs
Labels: internal

#1659 Make tests fail when tests fail
  bin/run-tests.mjs
Labels: internal

#1658 Additional coverage for each iteration with undefined item and specified key
  packages/@glimmer-workspace/integration-tests/test/keywords/each-test.ts
Labels: internal

#1669 Fix #1668: Node does not use the 'development' condition with default require() - this PR removes the `development` condition under `require` for `@glimmer/syntax` and dependents.
  packages/@glimmer/syntax/package.json
  packages/@glimmer/util/package.json
  packages/@glimmer/wire-format/package.json
Labels: bug
