Repository glimmerjs/glimmer-vm, pull requests merged in 2024-01, with the labels that each got.

#1544 Upgrade esyes
  package.json
  pnpm-lock.yaml
Labels: internal

#1553 add element parts, startTag & endTag
  packages/@glimmer/syntax/lib/parser/tokenizer-event-handlers.ts
  packages/@glimmer/syntax/lib/utils.ts
  packages/@glimmer/syntax/lib/v1/nodes-v1.ts
  packages/@glimmer/syntax/lib/v1/parser-builders.ts
  packages/@glimmer/syntax/lib/v1/public-builders.ts
  packages/@glimmer/syntax/lib/v1/visitor-keys.ts
  packages/@glimmer/syntax/test/loc-node-test.ts
  packages/@glimmer/syntax/test/parser-node-test.ts
Labels: enhancement

#1552 add block param nodes
  packages/@glimmer/syntax/lib/parser/handlebars-node-visitors.ts
  packages/@glimmer/syntax/lib/utils.ts
  packages/@glimmer/syntax/lib/v1/nodes-v1.ts
  packages/@glimmer/syntax/lib/v1/parser-builders.ts
  packages/@glimmer/syntax/lib/v1/public-builders.ts
  packages/@glimmer/syntax/lib/v1/visitor-keys.ts
  packages/@glimmer/syntax/test/loc-node-test.ts
  packages/@glimmer/syntax/test/parser-node-test.ts
Labels: enhancement

#1555 @glimmer/interfaces now uses extensions in its imports.
  packages/@glimmer/interfaces/index.d.ts
  packages/@glimmer/interfaces/lib/array.d.ts
  packages/@glimmer/interfaces/lib/compile/encoder.ts
  packages/@glimmer/interfaces/lib/compile/index.d.ts
  packages/@glimmer/interfaces/lib/compile/instruction-encoder.d.ts
  packages/@glimmer/interfaces/lib/compile/operands.d.ts
  packages/@glimmer/interfaces/lib/compile/wire-format/api.d.ts
  packages/@glimmer/interfaces/lib/components.d.ts
  packages/@glimmer/interfaces/lib/dom/attributes.d.ts
  packages/@glimmer/interfaces/lib/dom/bounds.d.ts
  packages/@glimmer/interfaces/lib/dom/changes.d.ts
  packages/@glimmer/interfaces/lib/dom/tree-construction.d.ts
  packages/@glimmer/interfaces/lib/managers.d.ts
  packages/@glimmer/interfaces/lib/managers/component.d.ts
  packages/@glimmer/interfaces/lib/managers/helper.d.ts
  packages/@glimmer/interfaces/lib/managers/internal.d.ts
  packages/@glimmer/interfaces/lib/managers/internal/component.d.ts
  packages/@glimmer/interfaces/lib/managers/internal/helper.d.ts
  packages/@glimmer/interfaces/lib/managers/internal/modifier.d.ts
  packages/@glimmer/interfaces/lib/managers/modifier.d.ts
  packages/@glimmer/interfaces/lib/program.d.ts
  packages/@glimmer/interfaces/lib/references.d.ts
  packages/@glimmer/interfaces/lib/runtime.d.ts
  packages/@glimmer/interfaces/lib/runtime/arguments.d.ts
  packages/@glimmer/interfaces/lib/runtime/debug-render-tree.d.ts
  packages/@glimmer/interfaces/lib/runtime/element.d.ts
  packages/@glimmer/interfaces/lib/runtime/environment.d.ts
  packages/@glimmer/interfaces/lib/runtime/helper.d.ts
  packages/@glimmer/interfaces/lib/runtime/modifier.d.ts
  packages/@glimmer/interfaces/lib/runtime/render.d.ts
  packages/@glimmer/interfaces/lib/runtime/runtime.d.ts
  packages/@glimmer/interfaces/lib/runtime/scope.d.ts
  packages/@glimmer/interfaces/lib/runtime/vm.d.ts
  packages/@glimmer/interfaces/lib/serialize.d.ts
  packages/@glimmer/interfaces/lib/stack.d.ts
  packages/@glimmer/interfaces/lib/template.d.ts
  packages/@glimmer/interfaces/package.json
  packages/@glimmer/interfaces/tsconfig.json
Labels: bug
