Repository glimmerjs/glimmer-vm, pull requests merged in 2025-03, with the labels that each got.

#1723 Add .npmrc to turbo.json
  turbo.json
Labels: internal

#1726 Move prettier tests to the smoke-tests project
  package.json
  packages/@glimmer-workspace/integration-node-tests/.gitignore
  packages/@glimmer-workspace/integration-node-tests/package.json
  pnpm-lock.yaml
  repo-metadata/metadata.json
  smoke-tests/node/package.json
  smoke-tests/node/tests/prettier.test.ts
Labels: internal

#1727 Update release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#1722 Printer bug: empty string literal args are dropped
  packages/@glimmer/syntax/lib/generation/printer.ts
  packages/@glimmer/syntax/test/generation/print-test.ts
Labels: bug

#1728 Set node-version to 22 in plan-release/publish
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
Labels: internal

#1729 Revert "Prepare Release"
  .release-plan.json
  CHANGELOG.md
  packages/@glimmer/compiler/package.json
  packages/@glimmer/destroyable/package.json
  packages/@glimmer/encoder/package.json
  packages/@glimmer/global-context/package.json
  packages/@glimmer/interfaces/package.json
  packages/@glimmer/manager/package.json
  packages/@glimmer/node/package.json
  packages/@glimmer/opcode-compiler/package.json
  packages/@glimmer/owner/package.json
  packages/@glimmer/program/package.json
  packages/@glimmer/reference/package.json
  packages/@glimmer/runtime/package.json
  packages/@glimmer/syntax/package.json
  packages/@glimmer/util/package.json
  packages/@glimmer/validator/package.json
  packages/@glimmer/vm-babel-plugins/package.json
  packages/@glimmer/vm/package.json
  packages/@glimmer/wire-format/package.json
  repo-metadata/metadata.json
Labels: internal

#1730 fix release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
Labels: internal

#1732 Fix bench post-install
  bin/bench-packages.mts
  bin/post-install.sh
  package.json
Labels: internal

#1734 Restore {{debugger}} behavior
  packages/@glimmer-workspace/build/lib/config.js
Labels: bug

#1735 Force release
  .release-plan.json
  packages/@glimmer/runtime/package.json
Labels: internal

#1736 pnpm repo:update:metadata
  repo-metadata/metadata.json
Labels: internal

#1741 Re-add support for tsconfig's moduleResolution=node10
  .meta-updater/main.mjs
  packages/@glimmer-workspace/benchmark-env/package.json
  packages/@glimmer/compiler/package.json
  packages/@glimmer/destroyable/package.json
  packages/@glimmer/encoder/package.json
  packages/@glimmer/global-context/package.json
  packages/@glimmer/manager/package.json
  packages/@glimmer/node/package.json
  packages/@glimmer/opcode-compiler/package.json
  packages/@glimmer/owner/package.json
  packages/@glimmer/program/package.json
  packages/@glimmer/reference/package.json
  packages/@glimmer/runtime/package.json
  packages/@glimmer/syntax/package.json
  packages/@glimmer/util/package.json
  packages/@glimmer/validator/package.json
  packages/@glimmer/vm/package.json
  packages/@glimmer/wire-format/package.json
Labels: bug

#1743 Upgrade handlebars parser
  packages/@glimmer/syntax/package.json
  pnpm-lock.yaml
Labels: enhancement

#1744 Upgrade to pnpm 10.6.5
  package.json
Labels: bug
